services:
  - type: web
    name: hrishi-tours-and-travels
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
